#!/bin/bash
# Script por GIAN modificações por Diego Canton

spfbl.sh superblock show | egrep "CIDR" | egrep "/32|/31|/30|/29|/28|/27|/26|/25" | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' > tmp1
awk '{ FS = "." } ; { print $1"."$2"."$3 }' tmp1 | sort | uniq --count | sort -n | egrep "[0-9]{2,4} " | awk -F" " '{print $2}' > tmp2
awk '{print "spfbl.sh superblock overlap "$0".0/24"}' tmp2 > tmp3
bash tmp3
cat tmp3
rm tmp*
