#!/bin/bash
# Script por Diego Canton
# Filtra o log do dia, por resultados com PASS ou FLAG, lista apenas os IPs organizados, exclui-se todos os repetidos;
# Filtra-se os IPs retirando-se os últimos digitos, contabiliza-se a quantidade de IPs cada faixa /24 possui;
# Os blocos com mais de 30 IPs são enviados para analise sobe o lista do dia

TODAY=`date +%Y-%m-%d`

egrep " SPFTCP[0-9]+ SPFBL " /var/log/spfbl/spfbl.$TODAY.log | grep PASS | awk -F" " '{print $9}' | sort | uniq | sed "s/'//g" | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' | awk '{ FS = "." } ; { print $1"."$2"."$3 }' | sort | uniq --count | sort -n | egrep "[0-9]{2,4} " | egrep "([0-9]+[0-9]{2}) |[3-9]+[0-9]+ " | awk -F" " '{print $2}' | awk '{print "spfbl.sh analise "$0".0/24 "$TODAY}'
