#!/bin/bash
spfbl.sh superblock show > tmp0
cat tmp0 | egrep "CIDR" | egrep "/32|/31|/30|/29|/28|/27|/26|/25" > tmp1
grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' tmp1 > tmp2
awk '{ FS = "." } ; { print $1"."$2"."$3 }' tmp2 > tmp3
sort tmp3 | uniq --count > tmp4
#print ranges count >10 tmp4 > tmp5
cat tmp4 | sort -n | egrep "[0-9]{2,4} " > tmp5
cat tmp5 | awk -F" " '{print $2}' > tmp6
awk '{print "spfbl.sh superblock overlap "$0".0/24"}' tmp6 > tmp7
bash tmp7
#cat tmp7
rm tmp*
